export const UPDATE_SOCKET = 'UPDATE_SOCKET'

export const SET_LOGIN = 'SET_LOGIN'

export const UPDATE_USERNAME = 'UPDATE_USERNAME'

export const UPDATE_CURRENT_ROOM_NAME = 'UPDATE_CURRENT_ROOM_NAME'

export const UPDATE_MESSAGES = 'UPDATE_MESSAGES'

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'

export const UPDATE_USERS = 'UPDATE_USERS'

export const UPDATE_JOINED_ROOMS = 'UPDATE_JOINED_ROOMS'

export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS'

export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE'

export const TOGGLE_CREATE_ROOM_FORM = 'TOGGLE_CREATE_ROOM_FORM'

export const TOGGLE_SEARCH_ROOM_FORM = 'TOGGLE_SEARCH_ROOM_FORM'

export const TOGGLE_SEARCH_USER_FORM = 'TOGGLE_SEARCH_USER_FORM'